name: Build OpenWrt Firmware
run-name: Build OpenWrt Firmware for ZTE E8820S ${{ inputs.repo_branch }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo_branch:
        description: 'OpenWrt branch or tag (e.g., openwrt-23.05, v23.05.3)'
        required: true
        default: 'openwrt-23.05'
        type: string

      config_link:
        description: 'Paste raw config file from pastebin'
        required: true
        type: string

      toolchain_link:
        description: 'URL to the pre-compiled toolchain tarball'
        required: true
        type: string
      
      llvm_link:
        description: 'URL to the pre-compiled LLVM BPF tarball'
        required: true
        type: string

      target_arch:
        description: 'Target architecture (e.g., ramips/mt7621)'
        required: true
        default: 'ramips/mt7621'
        type: string

      is_latest:
        description: 'Set the release as latest'
        default: false
        type: boolean

      is_prerelease:
        description: 'Set the release as pre-release'
        default: true
        type: boolean

permissions:
  contents: write

env:
  REPO_URL: https://github.com/openwrt/openwrt
  OPENWRT_RELEASE: ${{ github.event.inputs.repo_branch || 'openwrt-23.05' }}
  OPENWRT_TARGET: ${{ github.event.inputs.target_arch || 'ramips/mt7621' }}
  TOOLCHAIN_URL : ${{ github.event.inputs.toolchain_link || 'https://downloads.openwrt.org/releases/23.05.3/toolchain-mipsel_24kc_gcc-12.3.0_musl.Linux-x86_64.tar.xz' }}
  LLVM_URL : ${{ github.event.inputs.llvm_link || 'https://downloads.openwrt.org/releases/23.05.3/packages/mipsel_24kc/base/lld_16.0.6-2_mipsel_24kc.ipk' }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo apt-get clean

    - name: Install Build Dependencies
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget

    - name: Clone OpenWrt Source
      run: git clone --depth 1 $REPO_URL -b ${{ env.OPENWRT_RELEASE }} openwrt

    - name: Download External Toolchain
      run: |
        mkdir -p /opt/toolchain
        toolchain_name="${TOOLCHAIN_URL##*/}"
        llvm_name="${LLVM_URL##*/}"
        
        echo "Downloading $toolchain_name..."
        wget -q "$TOOLCHAIN_URL"
        tar -xf "$toolchain_name" -C /opt/toolchain --strip-components=2 --wildcards "*/toolchain-mipsel_24kc_gcc-*"
        rm "$toolchain_name"

        echo "Downloading $LLVM_URL..."
        wget -q "$LLVM_URL"
        tar -xf "$llvm_name" -C ./openwrt || touch ./openwrt/$llvm_name
        rm -f "$llvm_name"

    - name: Applying patch
      run: |
        cp patch/mt7621_zte_e8820s.dts openwrt/target/linux/ramips/dts/
        sed -i '/esac/e cat patch/leds.txt' openwrt/target/linux/ramips/mt7621/base-files/etc/board.d/01_leds || true
        sed -i '72r patch/upgrade.txt' openwrt/target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh || true
        cat patch/zte.txt >> openwrt/target/linux/ramips/image/mt7621.mk || true
        cp patch/99-default-settings openwrt/package/base-files/files/etc/uci-defaults/ || true
        
        if [ -d "files" ]; then
          echo "Injecting custom static config files..."
          cp -r files openwrt/
        fi

    - name: Update and Install Feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate Custom Configuration & Inject Toolchain
      working-directory: ./openwrt
      run: |
        if [ -n "${{ github.event.inputs.config_link }}" ]; then
          wget -q -O .config "${{ github.event.inputs.config_link }}"
        else
          make defconfig
        fi
        ./scripts/ext-toolchain.sh --toolchain /opt/toolchain --overwrite-config --config ${{ env.OPENWRT_TARGET }}

    - name: Append Custom Packages to .config
      working-directory: ./openwrt
      run: |
        echo "Mengaktifkan paket loadbalance, modem seluler, tema, dan aplikasi manajemen file..."
        
        sed -i '/CONFIG_PACKAGE_mwan3/d' .config
        sed -i '/CONFIG_PACKAGE_luci-app-mwan3/d' .config
        sed -i '/CONFIG_PACKAGE_luci-proto-3g/d' .config
        sed -i '/CONFIG_PACKAGE_chat/d' .config
        sed -i '/CONFIG_PACKAGE_comgt/d' .config
        sed -i '/CONFIG_PACKAGE_usb-modeswitch/d' .config
        sed -i '/CONFIG_PACKAGE_usbutils/d' .config
        sed -i '/CONFIG_PACKAGE_kmod-usb-net-rtl8152/d' .config
        sed -i '/CONFIG_PACKAGE_r8152-firmware/d' .config
        sed -i '/CONFIG_PACKAGE_kmod-usb3/d' .config
        sed -i '/CONFIG_PACKAGE_kmod-usb-xhci-mtk/d' .config
        sed -i '/CONFIG_PACKAGE_luci-app-filemanager/d' .config
        sed -i '/CONFIG_PACKAGE_luci-theme-material/d' .config
        
        cat << 'EOF' >> .config
        CONFIG_PACKAGE_mwan3=y
        CONFIG_PACKAGE_luci-app-mwan3=y
        CONFIG_PACKAGE_luci-proto-3g=y
        CONFIG_PACKAGE_chat=y
        CONFIG_PACKAGE_comgt=y
        CONFIG_PACKAGE_usb-modeswitch=y
        CONFIG_PACKAGE_usbutils=y
        CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
        CONFIG_PACKAGE_r8152-firmware=y
        CONFIG_PACKAGE_kmod-usb3=y
        CONFIG_PACKAGE_kmod-usb-xhci-mtk=y
        CONFIG_PACKAGE_luci-app-filemanager=y
        CONFIG_PACKAGE_luci-theme-material=y
EOF
        
        make defconfig

    - name: Download Packages
      working-directory: ./openwrt
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile OpenWrt
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        rm -rf bin/targets/ramips/mt7621/packages

    - name: Extract Vermagic
      id: get_vermagic
      run: |
        JSON_FILE="openwrt/bin/targets/ramips/mt7621/profiles.json"
        VERMAGIC=$(grep -oP '"vermagic":"\K[^"]+' "$JSON_FILE" || echo "unknown")
        
        VER_URL=$(dirname "${{ env.TOOLCHAIN_URL }}")

        if curl -s "$VER_URL/kmods/" | grep -q "$VERMAGIC"; then
          echo "vermagic=$VERMAGIC | ✅ Matched with Openwrt Official Build" >> $GITHUB_OUTPUT
        else
          echo "vermagic=$VERMAGIC | ❌ Mismatch with Openwrt Official Build" >> $GITHUB_OUTPUT
        fi

    - name: Generate Release Tag
      id: tag
      run: |
        echo "release_tag=${{ env.OPENWRT_RELEASE }}-$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
        echo "release_name=OpenWrt ZTE E8820S ${{ env.OPENWRT_RELEASE }} $(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: ${{ steps.tag.outputs.release_name }}
        prerelease: ${{ github.event.inputs.is_prerelease || 'true' }}
        make_latest: ${{ github.event.inputs.is_latest || 'false' }}
        files: openwrt/bin/targets/ramips/mt7621/*
        body: |
          ## ZTE E8820S OpenWrt Firmware ${{ env.OPENWRT_RELEASE }}
          Automated OpenWrt firmware build for ZTE E8820S.
          
          Version: ${{ env.OPENWRT_RELEASE }}
          Vermagic: ${{ steps.get_vermagic.outputs.vermagic }}
          *Compiled using pre-compiled OpenWrt toolchain*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
